name: deploy-to-aws
run-name: Deploy to AWS by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - CICD2

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Stop Server
        if: always()
        run: kill $(cat pid.txt) || true
      - name: Clean Up
        if: always()
        run: cd ${{ github.workspace }}; rm -rf Zoomy-Zodiacs;

  get:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - name: Checkout repository
        run: git clone https://github.com/Beardrop2/Zoomy-Zodiacs.git
      - run: cd Zoomy-Zodiacs; pwd; ls -la;

  build:
    runs-on: self-hosted
    needs: get
    defaults:
      run:
          working-directory: ./Zoomy-Zodiacs
    steps:
      - run: git checkout origin/CICD2
      - name: install
        run: pdm install
      - name: build
        run: pdm build

  test:
    runs-on: self-hosted
    needs: build
    defaults:
      run:
          working-directory: ./Zoomy-Zodiacs
    steps:
      - name: Run tests
        run: cd ${{ github.workspace }}; pdm run test
  
  run:
    runs-on: self-hosted
    needs: test
    defaults:
      run:
          working-directory: ./Zoomy-Zodiacs
    steps:
      - name: Start Bot
        run: cd ${{ github.workspace }}; pdm run start
