name: deploy-to-aws
run-name: Deploy to AWS by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        # You are now able to use PDM in your workflow
      - name: build
        run: pdm build

  test:
    runs-on: self-hosted
    steps:
      - name: Set env
        run: source ./.env/bin/activate
      - name: ensure pip
        run: python -m ensurepip
      - name: install
        run: python -m pip install ./dist/*.whl  --force-reinstall
      - name: Run Tests
        run: pdm run pytest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - run: echo RUN!