name: deploy-to-aws
run-name: Deploy to AWS by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - CICD2

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        run: git clone ${{ env.repository_url }};
      - run: cd $(basename ${{ github.repository }} .git);
      - run: git fetch origin ${{ github.ref_name }};
      - run: git checkout ${{ github.ref_name }};
      - name: Environment
        run: source ./.venv/bin/activiate
      - name: build
        run: pdm build
      - name: install
        run: pdm install
      - name: Stop bot # PDM install required before stop script
        run: pdm run stop
      - name: Run pre-commit hooks
        run: pdm run pre-commit
      - name: Run tests
        run: pdm run test
      - name: Start Bot
        run: pdm run start
