name: deploy-to-aws
run-name: Deploy to AWS by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - CICD2

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Stop Server
        if: always()
        run: kill $(cat pid.txt) || true
      - name: Clean Up
        if: always()
        run: cd ${{ github.workspace }}; rm -rf Zoomy-Zodiacs;

  build:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - name: Checkout repository
        run: git clone https://github.com/Beardrop2/Zoomy-Zodiacs.git
      - name: wait
        run: sleep 10 # For some reason, the action seems to checkout before the clone is done.
      - run: cd $(basename ${{ github.repository }} .git);
      - run: git fetch origin ${{ github.ref_name }};
      - run: git checkout ${{ github.ref_name }};
      - name: Environment
        run: source ./.venv/bin/activiate
      - name: Run pre-commit hooks
        run: pdm run pre-commit
      - name: build
        run: pdm build
      - name: install
        run: pdm install

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run tests
        run: pdm run test
  
  run:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Start Bot
        run: pdm run start
