name: deploy-to-aws
run-name: Deploy to AWS by @${{ github.actor }}

on:
  push:
    branches:
      - main
      - CICD2

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Stop Server
        if: always()
        run: kill $(cat pid.txt) || true
      - name: Clean Up
        if: always()
        run: cd ${{ github.workspace }}; rm -rf Zoomy-Zodiacs;

  build:
    runs-on: self-hosted
    needs: cleanup
    steps:
      - name: Checkout repository
        run: git clone https://github.com/Beardrop2/Zoomy-Zodiacs.git
      - run: cd Zoomy-Zodiacs; pwd; ls -la;
      - run: cd ${{ github.workspace }}; git checkout origin/CICD2
      - name: Environment
        run: cd ${{ github.workspace }}; source ./.venv/bin/activiate
      - name: Run pre-commit hooks
        run: cd ${{ github.workspace }}; pdm run pre-commit
      - name: install
        run: cd ${{ github.workspace }}; pdm install
      - name: build
        run: cd ${{ github.workspace }}; pdm build

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run tests
        run: cd ${{ github.workspace }}; pdm run test
  
  run:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Start Bot
        run: cd ${{ github.workspace }}; pdm run start
